# Generated by Django 3.1.7 on 2021-04-28 07:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(max_length=255)),
                ('rent_price', models.FloatField()),
                ('area', models.FloatField()),
                ('pop', models.FloatField()),
                ('dist_of_ind', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectInfrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('radius', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_create', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectIntersections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326)),
                ('area', models.FloatField()),
                ('obj_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objectbusiness')),
                ('obj_infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objectinfrastructure')),
            ],
        ),
        migrations.AddField(
            model_name='objectinfrastructure',
            name='obj_research',
            field=models.ManyToManyField(to='main.ObjectResearch'),
        ),
        migrations.AddField(
            model_name='objectbusiness',
            name='obj_research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.objectresearch'),
        ),
    ]
