# Generated by Django 3.1.7 on 2021-04-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectbusiness',
            name='source',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
